const allData = [
  {  
    id: 1,
    image: 'https://m.media-amazon.com/images/I/81yh8+MHWHL.jpg',
    title: 'Street Cruiser',
    description: 'Classic maple wood skateboard',
    price: 1599,
    sale: 'Sale',
    saleprice: '1899',
  },
  {
    id: 2,
    image: 'https://cdn.canvaschamp.in/static/images/landingpage/skateboard-deck/skateboard-deck-2.jpg',
    title: 'Pro Deck',
    description: 'High-performance street deck',
    price: 2299,
    sale: '',
    saleprice: '',
  },
  {
    id: 3,
    image: 'https://m.media-amazon.com/images/I/61agiTSziEL.jpg',
    title: 'Mini Cruiser',
    description: 'Compact plastic cruiser board',
    price: 1299,
    sale: '',
    saleprice: '',
  },
  {
    id: 4,
    image: 'https://images-cdn.ubuy.co.in/633bcf80e2284054d803a223-chromewheels-31.jpg',
    title: 'Downhill Beast',
    description: 'Longboard for high-speed carving',
    price: 2999,
    sale: 'Sale',
    saleprice: '3499',
  },
  {
    id: 5,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTFUV-VNjIKhFbv9r2WYrRFUkHjpWDvm74qA&s',
    title: 'Pro Deck',
    description: 'High-performance street deck',
    price: 2299,
    sale: '',
    saleprice: '',
  },
  {
    id: 6,
    image: 'https://m.media-amazon.com/images/I/81yh8+MHWHL.jpg',
    title: 'Street Cruiser',
    description: 'Classic maple wood skateboard',
    price: 1599,
    sale: 'Sale',
    saleprice: '1899',
  },
  {
    id: 7,
    image: 'https://cdn.canvaschamp.in/static/images/landingpage/skateboard-deck/skateboard-deck-2.jpg',
    title: 'Pro Deck',
    description: 'High-performance street deck',
    price: 2299,
    sale: '',
    saleprice: '',
  },
  {
    id: 8,
    image: 'https://m.media-amazon.com/images/I/61agiTSziEL.jpg',
    title: 'Mini Cruiser',
    description: 'Compact plastic cruiser board',
    price: 1299,
    sale: '',
    saleprice: '',
  },
  {
    id: 9,
    image: 'https://images-cdn.ubuy.co.in/633bcf80e2284054d803a223-chromewheels-31.jpg',
    title: 'Downhill Beast',
    description: 'Longboard for high-speed carving',
    price: 2999,
    sale: 'Sale',
    saleprice: '3499',
  },
  {
    id: 10,
    image: 'https://m.media-amazon.com/images/I/81yh8+MHWHL.jpg',
    title: 'Street Cruiser',
    description: 'Classic maple wood skateboard',
    price: 1599,
    sale: 'Sale',
    saleprice: '1899',
  },
  {
    id: 11,
    image: 'https://cdn.canvaschamp.in/static/images/landingpage/skateboard-deck/skateboard-deck-2.jpg',
    title: 'Pro Deck',
    description: 'High-performance street deck',
    price: 2299,
    sale: '',
    saleprice: '',
  },
  {
    id: 12,
    image: 'https://m.media-amazon.com/images/I/61agiTSziEL.jpg',
    title: 'Mini Cruiser',
    description: 'Compact plastic cruiser board',
    price: 1299,
    sale: '',
    saleprice: '',
  },
  {
    id: 13,
    image: 'https://images-cdn.ubuy.co.in/633bcf80e2284054d803a223-chromewheels-31.jpg',
    title: 'Downhill Beast',
    description: 'Longboard for high-speed carving',
    price: 2999,
    sale: 'Sale',
    saleprice: '3499',
  },
  {
    id: 14,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTFUV-VNjIKhFbv9r2WYrRFUkHjpWDvm74qA&s',
    title: 'Pro Deck',
    description: 'High-performance street deck',
    price: 2299,
    sale: '',
    saleprice: '',
  },
  { 
    id: 15,
    image: 'https://m.media-amazon.com/images/I/81yh8+MHWHL.jpg',
    title: 'Street Cruiser',
    description: 'Classic maple wood skateboard',
    price: 1599,
    sale: 'Sale',
    saleprice: '1899',
  },
  {
    id: 16,
    image: 'https://cdn.canvaschamp.in/static/images/landingpage/skateboard-deck/skateboard-deck-2.jpg',
    title: 'Pro Deck',
    description: 'High-performance street deck',
    price: 2299,
    sale: '',
    saleprice: '',
  },
  {
    id: 17,
    image: 'https://m.media-amazon.com/images/I/61agiTSziEL.jpg',
    title: 'Mini Cruiser',
    description: 'Compact plastic cruiser board',
    price: 1299,
    sale: '',
    saleprice: '',
  },
  {
    id: 18,
    image: 'https://images-cdn.ubuy.co.in/633bcf80e2284054d803a223-chromewheels-31.jpg',
    title: 'Downhill Beast',
    description: 'Longboard for high-speed carving',
    price: 2999,
    sale: 'Sale',
    saleprice: '3499',
  },
];
export default allData;